const express=require("express");
const app=express();

app.get('/api/users',(req,resp)=>{
    const users=[
       
        {
            id:1,
            user:"Suvi",
            email:"suvi@gmail.com",
            password:'Suvi#123_01'
        },
        {
            id:2,
            user:"Subhangi",
            email:"subhangi@gmail.com",
            password:'Subh#123_26'
        },
        {
            id:3,
            user:"Sanchi",
            email:"sanchi@gmail.com",
            password:'Sanchi#123_13'
        },
        {
            id:4,
            user:"Priyansi",
            email:"priyanshi@gmail.com",
            password:'Priya#123_21'
        },
        {
            id:5,
            user:"Neha",
            email:"neha@gmail.com",
            password:'Neha#123_14'
        },
        {
            id:6,
            user:"Richa",
            email:"richa@gmail.com",
            password:'Richa#123_13'
        },
        {
            id:7,
            user:"Priya",
            email:"priya@gmail.com",
            password:'Priya#123_15'
        },
        {
            id:8,
            user:"Binni",
            email:"binni@gmail.com",
            password:'Binni#123_11'
        },
        {
            id:9,
            user:"Kavita",
            email:"kavita@gmail.com",
            password:'Kavita#123_11'
        },
        {
            id:10,
            user:"Dipti",
            email:"dipti@gmail.com",
            password:'Dipti#123_01'
        },
        {
            id:11,
            user:"Prity",
            email:"prity@gmail.com",
            password:'prity#123_21'
        },
        {
            id:12,
            user:"Sweeta",
            email:"sweeta@gmail.com",
            password:'Sweeta#123_20'
        },
        {
            id:13,
            user:"Purvi",
            email:"Puri@gmail.com",
            password:'Purvi#123_15'
        },
        {
            id:14,
            user:"Pihu",
            email:"pihu@gmail.com",
            password:'Pihu#123_13'
        },
        {
            id:15,
            user:"Pravika",
            email:"pravika@gmail.com",
            password:'Pravikai#123_26'
        },
        {
            id:16,
            user:"Kiran",
            email:"kiran@gmail.com",
            password:'Kiran#123_13'
        },
        {
            id:17,
            user:"Sangita",
            email:"sangita@gmail.com",
            password:'Sangita#123_12'
        },
        {
            id:18,
            user:"Naini",
            email:"naini@gmail.com",
            password:'Naini#123_15'
        },
        {
            id:19,
            user:"Neelam",
            email:"neelam@gmail.com",
            password:'Neelam#123_18'
        },
        {
            id:20,
            user:"Rita",
            email:"rita@gmail.com",
            password:'Rita#123_15'
        }
    ];
    resp.send(users);
});